---
- name: test
  become: yes
  hosts: 
    - zone_a
    - zone_b
  tasks:
    - name: Ensure DHCP Package is at latest version
      ansible.builtin.package:
        name: dhcp-server
        state: present
    - name: Create DHCP Configuration from Template
      template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
      notify:
        - Restart dhcpd
    - name: Enable DHCP Service
      ansible.builtin.service:
        name: dhcpd
        state: started
        enabled: true
    - name: Immediately disable it, so I dont mess up my network
      ansible.builtin.service:
        name: dhcpd
        state: stopped
        enabled: false
  handlers:
    - name: Restart dhcpd
      ansible.builtin.service:
        name: dhcpd
        state: restarted
